export {default as billie_eilish} from './billie_eilish.jpg'
export {default as danny_carry} from './danny_carry.jpeg'
export {default as degrass_tyson } from './degrass_tyson.jpg'
export {default as dennis_rodman } from './dennis_rodman.jpg'
export {default as lady_gaga} from './lady_gaga.jpeg'
export {default as netta} from './netta.jpg'
export {default as nicky_minaj} from './nicky_minaj.jpeg'
export {default as peled} from './peled.jpeg'
export {default as rupaul} from './rupaul.jpeg'